server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: qa
    label : test
  cloud:
    config:
      server:
        git:
          uri: file:///udemy/git-localconfig-repo


limit-service:
  minimun: 9
  maximun: 9999